/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = string;

/**
 * A Versa itinerary
 */
export interface Itinerary {
  schema_version: SchemaVersion;
  header: Header;
  itemization: Itemization;
  footer: Footer;
}
export interface Header {
  third_party?: {
    relation:
      | "bnpl"
      | "delivery_service"
      | "marketplace"
      | "payment_processor"
      | "platform"
      | "point_of_sale";
    /**
     * Determines whether the merchant or third party gets top billing on the receipt
     */
    make_primary: boolean;
    merchant?: Org | null;
  } | null;
  customer?: Customer | null;
}
export interface Org {
  name: string;
  /**
   * Hex color
   */
  brand_color?: string | null;
  legal_name?: string | null;
  logo?: string | null;
  logo_asset_id?: string | null;
  website?: string | null;
  vat_number?: string | null;
  address?: null | Address;
}
export interface Address {
  street_address?: string | null;
  city?: string | null;
  region?: null | string;
  country?: null | string;
  postal_code?: string | null;
  lat?: number | null;
  lon?: number | null;
  tz?: string | null;
}
export interface Customer {
  name: string;
  email?: string | null;
  website?: string | null;
  address?: null | Address;
  phone?: string | null;
  metadata?: null | Metadatum[];
}
export interface Metadatum {
  key: string;
  value: string;
}
export interface Itemization {
  lodging?: Lodging | null;
  car_rental?: CarRental | null;
  service?: Service | null;
  transit_route?: TransitRoute | null;
  flight?: Flight | null;
}
export interface Lodging {
  check_in: number;
  check_out: number;
  location: Place;
  /**
   * @minItems 1
   */
  items: Item[];
  room?: null | string;
  guests?: null | Person[];
  metadata?: null | Metadatum[];
}
/**
 * The physical or online location where a transaction occurred
 */
export interface Place {
  name?: string | null;
  address?: null | Address;
  phone?: string | null;
  url?: null | string;
  google_place_id?: string | null;
  image?: null | string;
}
export interface Item {
  date?: null | string;
  description: string;
  quantity?: null | number;
  unit?: null | string;
  unspsc?: null | string;
  metadata?: null | Metadatum[];
  product_image_asset_id?: string | null;
  group?: null | string;
  url?: null | string;
}
export interface Person {
  first_name?: string | null;
  last_name?: string | null;
  preferred_first_name?: string | null;
  email?: string | null;
  phone?: string | null;
  metadata?: null | Metadatum[];
}
export interface CarRental {
  rental_at: number;
  return_at: number;
  rental_location: Place;
  return_location: Place;
  vehicle?: {
    description: string;
    license_plate_number?: string | null;
    vehicle_class?: string | null;
    image?: string | null;
  } | null;
  driver_name: string;
  odometer_reading_in: number;
  odometer_reading_out: number;
  /**
   * @minItems 1
   */
  items: Item[];
  metadata?: null | Metadatum[];
}
export interface Service {
  /**
   * @minItems 1
   */
  service_items: ServiceItem[];
}
export interface ServiceItem {
  description: string;
  service_location?: Place | null;
  current_period_start_at?: number | null;
  current_period_end_at?: number | null;
  metadata?: null | Metadatum[];
}
export interface TransitRoute {
  /**
   * @minItems 1
   */
  transit_route_items: TransitRouteItem[];
}
export interface TransitRouteItem {
  departure_location?: null | Place;
  arrival_location?: null | Place;
  departure_at?: number | null;
  arrival_at?: number | null;
  polyline?: null | string;
  metadata?: null | Metadatum[];
  passenger?: null | Person;
  mode?: null | ("car" | "taxi" | "rail" | "bus" | "ferry" | "other");
}
export interface Flight {
  /**
   * @minItems 1
   */
  tickets: FlightTicket[];
  itinerary_locator?: null | string;
}
export interface FlightTicket {
  /**
   * @minItems 1
   */
  segments: FlightSegment[];
  number?: null | string;
  record_locator?: null | string;
  passenger?: null | Person;
}
export interface FlightSegment {
  departure_airport_code: string;
  arrival_airport_code: string;
  aircraft_type?: null | string;
  departure_at?: null | number;
  arrival_at?: null | number;
  departure_tz?: null | string;
  arrival_tz?: null | string;
  flight_number?: null | string;
  seat?: null | string;
  class_of_service?: null | string;
  metadata?: null | Metadatum[];
}
export interface Footer {
  supplemental_text?: string | null;
}
