/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A Versa itemized receipt
 */
export interface Receipt {
  schema_version: string;
  header: {
    invoice_number: string | null;
    /**
     * ISO 4217 currency code
     */
    currency: "usd" | "eur" | "jpy" | "gbp" | "aud" | "cad" | "chf" | "cnh";
    total: number;
    subtotal: number;
    paid: number;
    invoiced_at: number;
    mcc: string | null;
    third_party: {
      first_party_relation:
        | "bnpl"
        | "delivery_service"
        | "marketplace"
        | "payment_processor"
        | "platform"
        | "point_of_sale";
      /**
       * Determines whether the merchant or third party gets top billing on the receipt
       */
      make_primary: boolean;
      merchant: Org;
    } | null;
    customer: {
      name: string;
      email: string | null;
      address: null | Address;
      phone: string | null;
      metadata: ItemMetadata[];
    } | null;
    location: Place | null;
  };
  itemization: Itemization;
  actions: {
    name: string;
    url: string;
  }[];
  payments: Payment[];
}
export interface Org {
  name: string;
  brand_color: string | null;
  legal_name: string | null;
  logo: string | null;
  website: string | null;
  vat_number: string | null;
  address: null | Address;
}
export interface Address {
  street_address: string | null;
  city: string | null;
  region: null | string;
  country: null | string;
  postal_code: string | null;
  lat: number | null;
  lon: number | null;
  tz: string | null;
}
export interface ItemMetadata {
  key: string;
  value: string;
}
export interface Place {
  name: string | null;
  address: null | Address;
  phone: string | null;
  url: null | string;
  google_place_id: string | null;
  image: null | string;
}
export interface Itemization {
  general: GeneralItemization | null;
  lodging: Lodging | null;
  ecommerce: Ecommerce | null;
  car_rental: CarRental | null;
  transit_route: TransitRoute | null;
  subscription: Subscription | null;
  flight: Flight | null;
}
export interface GeneralItemization {
  /**
   * @minItems 1
   */
  line_items: Item[];
  invoice_level_adjustments: Adjustment[];
}
export interface Item {
  date?: null | string;
  description: string;
  subtotal: number;
  quantity?: null | number;
  unit_cost?: null | number;
  unit?: null | string;
  unspsc?: null | string;
  taxes?: Tax[];
  metadata?: ItemMetadata[];
  product_image?: null | string;
  group?: null | string;
  url?: null | string;
  adjustments?: Adjustment[];
}
export interface Tax {
  amount: number;
  rate: number | null;
  name: string;
}
export interface Adjustment {
  amount: number;
  name: null | string;
  adjustment_type: "discount" | "tip" | "fee" | "other";
  rate: null | number;
}
export interface Lodging {
  check_in: number;
  check_out: number;
  location: Place;
  /**
   * @minItems 1
   */
  items: Item[];
  room?: null | string;
  guests?: null | string;
  metadata?: ItemMetadata[];
  invoice_level_adjustments: Adjustment[];
}
export interface Ecommerce {
  shipments: {
    /**
     * @minItems 1
     */
    items: Item[];
    tracking_number: string | null;
    expected_delivery_at: number | null;
    shipment_status: ("prep" | "in_transit" | "delivered") | null;
    destination_address: null | Address;
  }[];
  invoice_level_line_items: Item[];
  invoice_level_adjustments: Adjustment[];
}
export interface CarRental {
  rental_at: number;
  return_at: number;
  rental_location: Place;
  return_location: Place;
  vehicle: {
    description: string;
    image: string | null;
  } | null;
  driver_name: string;
  odometer_reading_in: number;
  odometer_reading_out: number;
  /**
   * @minItems 1
   */
  items: Item[];
  invoice_level_adjustments: Adjustment[];
}
export interface TransitRoute {
  /**
   * @minItems 1
   */
  transit_route_items: {
    departure_location: null | Place;
    arrival_location: null | Place;
    departure_at: number | null;
    arrival_at: number | null;
    polyline: null | string;
    taxes: Tax[];
    metadata: ItemMetadata[];
    fare: number;
    passenger: string | null;
    mode?: ("car" | "taxi" | "rail" | "bus" | "ferry" | "other") | null;
  }[];
  invoice_level_adjustments: Adjustment[];
}
export interface Subscription {
  /**
   * @minItems 1
   */
  subscription_items: {
    subtotal: number;
    subscription_type: "one_time" | "recurring";
    description: string;
    interval: null | ("day" | "week" | "month" | "year");
    interval_count: number | null;
    current_period_start: number | null;
    current_period_end: number | null;
    quantity: number | null;
    unit_cost: number | null;
    taxes: Tax[];
    metadata: ItemMetadata[];
    adjustments: Adjustment[];
  }[];
  invoice_level_adjustments: Adjustment[];
}
export interface Flight {
  /**
   * @minItems 1
   */
  tickets: FlightTicket[];
  itinerary_locator: null | string;
  invoice_level_adjustments: Adjustment[];
}
export interface FlightTicket {
  /**
   * @minItems 1
   */
  segments: FlightSegment[];
  number: null | string;
  record_locator: null | string;
  passenger: null | string;
}
export interface FlightSegment {
  fare: number;
  departure_airport_code: string;
  arrival_airport_code: string;
  departure_at: null | number;
  arrival_at: null | number;
  departure_tz: null | string;
  arrival_tz: null | string;
  flight_number: null | string;
  class_of_service: null | string;
  taxes: Tax[];
  adjustments: Adjustment[];
}
export interface Payment {
  amount: number;
  paid_at: number;
  payment_type: "card" | "ach";
  card_payment: null | CardPayment;
  ach_payment: null | AchPayment;
}
export interface CardPayment {
  last_four: string;
  network:
    | (
        | "amex"
        | "diners"
        | "discover"
        | "eftpos_au"
        | "jcb"
        | "mastercard"
        | "unionpay"
        | "visa"
      )
    | null;
}
export interface AchPayment {
  routing_number: string;
}
